#!?bin/bash

if [ ${UID} -ne 0 ]
then
echo
echo "You need root access"
echo
exit 0
fi

## Check number of cpu

if [ `nproc` -eq 1 ]
then
echo "This server is very small"
exit2
fi

## check memory

free -m

## check the OS version

cat /etc/*release
